# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Matthew Einhorn
email: moiein2000@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Website for personal and work projects and my blog
twitter_username:
github_username: matham
minimal_mistakes_skin: dark
search: true

# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes@4.16.6"
repository: matham/matham.github.io
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /blog/page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages
  - _software_projects
  - _hardware_projects
  - _ml
  - _portfolio

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Matthew Einhorn"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "I'm curious about the world."
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://matham.dev"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/matham"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/matham"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  # _portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: false
      share: false
  # _ml
  - scope:
      path: ""
      type: ml
    values:
      layout: single
      author_profile: false
      share: false
  # _hardware_projects
  - scope:
      path: ""
      type: hardware_projects
    values:
      layout: single
      author_profile: true
      classes: wide
      share: false
  # _software_projects
  - scope:
      path: ""
      type: software_projects
    values:
      layout: single
      author_profile: true
      classes: wide
      share: false

# Collections
collections:
  ml:
    output: true
    permalink: /:collection/:path/
  software_projects:
    output: true
    permalink: /:collection/:path/
  hardware_projects:
    output: true
    permalink: /:collection/:path/


category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
